"use client"
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "../components/navBar";
import { useEffect } from "react";
import axios from "axios";
import Cookies from "js-cookie";
import { useRouter } from "next/navigation";
import { useDispatch } from "react-redux";
import { setUser } from "../states/user";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const dispatch=useDispatch()
  const router=useRouter()

  useEffect(() => {
    axios
      .get("http://localhost:4000/api/v1/user/me", {
        headers: {
          cookies: `${Cookies.get("token")}`,
        },
      })
      .then((response) => {
        console.log( response.data);
        dispatch(setUser(response.data))
      })
      .catch(({ error }) => {
        console.error(error)
        router.push("/login")
      });
 
  }, []);


  return (
    <div>
      <NavBar />
      <div>{children}</div>
    </div>
  );
}
